version: "3.5"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: root
    network_mode: host
    volumes:
      - ${HOME}/.config/jellyfin:/config
      - ${HOME}/server_nas/jellyfin/cache:/cache
      - ${HOME}/server_nas/qbittorrent/downloads:/media
      - ${HOME}/server_nas/jellyfin/media2:/media2:ro
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${HOME}/.config/qbittorrent/config:/config
      - ${HOME}/server_nas/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/.config/sonarr/config:/config
      - ${HOME}/server_nas/sonarr/tvseries:/tv #optional
      - ${HOME}/server_nas/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
